name: wallpaperworld
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  async_wallpaper: ^2.0.3
  fab_circular_menu: ^1.0.2
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.0.0
  fluttertoast: ^8.2.8
  http: ^1.2.0
  icons_launcher: ^3.0.0
  introduction_screen: ^3.1.12
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - shorebird.yaml


icons_launcher:
  image_path: "assets/elephant_transparent.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true